### ISSUE TITLE
BadRequest Error from Faraday

### ISSUE THREAD

**Issue by daBee** [alchaplinsky/gen-ai#7]
```
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.11/lib/faraday/response/raise_error.rb:16:in `on_complete': the server responded with status 400 (Faraday::BadRequestError)
```

Culprit: 
```
result = model.generate('a large bucket of beer')
```

**Comment by alchaplinsky** [comment]
@daBee How do you instantiate a `model`?

**Comment by daBee** [comment]
```
require 'gen_ai'
model = GenAI::Image.new(:open_ai, GPT_KEY)
result = model.generate('a large bucket of beer')
```

**Comment by alchaplinsky** [comment]
@daBee  Also, can you provide a full error trace?

**Comment by daBee** [comment]
```
Exception Message: the server responded with status 400
Error Trace:
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.11/lib/faraday/response/raise_error.rb:16:in `on_complete'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.11/lib/faraday/middleware.rb:18:in `block in call'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.11/lib/faraday/response.rb:42:in `on_complete'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.11/lib/faraday/middleware.rb:17:in `call'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.11/lib/faraday/rack_builder.rb:153:in `build_response'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.11/lib/faraday/connection.rb:444:in `run_request'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.11/lib/faraday/connection.rb:280:in `post'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-openai-6.0.0/lib/openai/http.rb:12:in `json_post'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-openai-6.0.0/lib/openai/images.rb:8:in `generate'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gen-ai-0.2.2/lib/gen_ai/image/open_ai.rb:18:in `block in generate'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gen-ai-0.2.2/lib/gen_ai/base.rb:12:in `handle_errors'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gen-ai-0.2.2/lib/gen_ai/image/open_ai.rb:18:in `generate'
/Users/rich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gen-ai-0.2.2/lib/gen_ai/image.rb:10:in `generate'
/users/rich/app.rb:113:in `<main>'
Exception Message: divided by 0
Error Trace:
/users/rich/app.rb:148:in `/'
/users/rich/app.rb:148:in `<main>'
```

**Comment by alchaplinsky** [comment]
So you've got a 400 response from OpenAI's API for some reason. The prompt looks good, so I think there might be something wrong with your `GPT_KEY` or your API access in general. Your code works fine for me.

**Comment by alchaplinsky** [comment]
Result:
![tmp](https://github.com/alchaplinsky/gen-ai/assets/695947/53283e90-9b42-4117-9bc9-710f8d5af479)

**Comment by daBee** [comment]
OK, I'll take another look.  I would think that the key provided would have responded accordingly.
